version: '3.3'
services:
  npm2pihole:
    image: ghcr.io/c00ldude1oo/npm2pihole:latest
    env_file: config.env
    volumes:
        # Path to Nginx Proxy Mangers data/nginx/proxy_host folder.
      - /path/to/npm/data/nginx/proxy_host/:/app/npm/:ro
        # PiHole's /etc/pihole/custom.list file. commit if remote pihole
#      - /path/to/piholes/data/custom.list:/app/custom.list
        # SSH key(s) for sftp. commit if unused
      - ./ssh/:/root/.ssh/
